### ISSUE TITLE
OBC-DB: Temperature Sensor Circuit Development

### ISSUE THREAD

**Issue by jillianmalherbe** [queens-satellite-team/pcbs#15]
# Motivation ⛰️ 
> A temperature sensor is needed in order to monitor the temperature on OBC Daughterboard. Last year, the OBC V1 featured an integrated temperature sensor circuit although due to time constraints, we were not able to test and iterate upon its design. The plan is to have a fully functional and tested temperature sensor which we can include in the CDR presentation (October 24th).

# Next Steps 🚶 

- [ ] Check out the design for last year's temperature sensor circuit which can be found in the "OBC V1 Documentation" Word Doc.
- [ ] The components used in last year's circuit can be found in the team's 2021-2022 BOM for the OBC V1. Take a look at the datasheet for the main temperature sensor component and try to understand how this component works with the current circuit configuration. 
- [ ] Research alternative configurations on the internet and determine if any changes need to be made to the current design.
- [ ] Develop a testing plan for the ciruit (LT Spice is recommended but you may also choose to build the circuit out physically and test from there). 
- [ ] Complete the testing. We need proof that it works.
- [ ] Clone the latest OBC-DB KiCad files from the pcbs repository. Create the Circuit in the project's KiCad Schematic and push your changes to the pcbs repository. 

# Supporting Material and Resources 📖 

- [OBC V1 Documentation](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-OBC/OBC%202021-2022/OBC%20V1%20Documentation.docx?d=wbe27c4fe86f64b30a6ad24559bc99bfa&csf=1&web=1&e=XpoLQm)
- [OBC Design Document](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-General/csdc/4000-systems-design/csdc-4500-on-board-computer-design/[csdc-4501-rpi-and-obc-db-requirements.docx](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-General/csdc/4000-systems-design/csdc-4500-on-board-computer-design/csdc-4501-rpi-and-obc-db-requirements.docx?d=w3b0bc17a7c5940788b19de2c4d372e7d&csf=1&web=1&e=qBf7Wd)?d=w3b0bc17a7c5940788b19de2c4d372e7d&csf=1&web=1&e=qBf7Wd)
- Last year's KiCad files can be found in the pcbs repository under "STM32 Breakout"
-[STM32 Breakout](https://github.com/queens-satellite-team/pcbs/tree/master/OBC_Boards)
- [OBC Daughterboard KiCad](https://github.com/queens-satellite-team/pcbs/tree/master/OBC_Boards)

# Definition of Done 💯 
> A fully tested and functional design for a temperature sensor circuit can be found in the Team's KiCad files. A description detailing your choice of components as well as circuit specifications can be found in the team's design document.

### Tags

cc: @SeanTedesco @emmapaczkowski @sirlipski @jillianmalherbe

**Comment by SeanTedesco** [comment]
Temperature sensor circuit has been designed and tested on the OBC-DB. Closing issue.
