### ISSUE TITLE
Daughterboard Layout

### ISSUE THREAD

**Issue by jillianmalherbe** [queens-satellite-team/pcbs#30]
# Motivation ⛰️ 
> The layout for the OBC daughterboard needs to be completed. 

# Next Steps 🚶 

- [x] Refer to the high level block diagram which can be found in the OBC Design Notes when determining where to place components.
- [x] Use the correct trace width (0.5mm for 5v, 0.4mm for 3V3 and 0.2mm for data traces)
- [x] Avoid putting back traces until absolutely necessary. Try to have traces going in the same direction follow the same path.

# Supporting Material and Resources 📖 

# Definition of Done 💯 
> All components are placed on the board and are correctly connected using traces. 

### Tags
> tag people that should know about this issue

cc: @SeanTedesco @emmapaczkowski

**Comment by SeanTedesco** [comment]
OBC-DB has finished its layout, closing this issue
