### ISSUE TITLE
Umbillical Debug Interface Board

### ISSUE THREAD

**Issue by jillianmalherbe** [queens-satellite-team/pcbs#9]
# Motivation ⛰️ 
> We need a way to plug into the OBC and get status updates without needing to disassemble the Selfie-Sat. Thus, the team will be designing and assembling an additional custom PCB which we will call the Umbilical Debug Interface Board (OBC-IB). This board will be populated with ports and LED's and will also contain some ports that will be routed directly to the EPS subsystem (such as a battery charging port). The idea is to eventually have this board positioned parallel to the outer wall of the satellite with the LED light exposed and we want the front of the ports to be flush with the outer wall of the CubeSat. Certain components such as the Ethernet Interface will be routed directly to the Rpi-4 ethernet port while others will be routed to the daughterboard through a connector.
> We want to have all of the components selected before CDR (October 24th) so that we can include our preliminary design in the presentation. It might also be nice to have an initial layout for the board completed for the presentation but we'll see how things progress.

# Next Steps 🚶 

- [ ] Read through the requirements needed for this project which can be found in the OBC design document under 6.4.3 "Umbilical Debugging Interface Board"
- [ ] Research ports and components that would be good to have on the board based on the listed requirements. Make a list of these components.
- [ ] Communicate with the mech team, specifically @TyeD to discuss dimensions for the board and where it will be located on the Selfie Sat.
- [ ] Create a KiCad schematic file for the PCB in the pcbs repository. (Ask @jillianmalherbe or @sirlipski for help if you're unsure)
- [ ] Insert the symbols and footprints for the selected components into the KiCad schematic. The board must also include a PMOD connector which will be routed to the OBC Daughterboard.
- [ ] In KiCad, make the PCB the correct dimensions that were decided upon with the mech team. Complete the layout for the PCB by dragging components onto the CAD board and drawing the appropriately sized traces between components, LED's and connectors. (We will have a tutorial on this when the time comes)
- [ ] Present the board to the team during one of our OBC Design Reviews, get feedback and iterate upon the design.

# Supporting Material and Resources 📖 

- This project mostly involves using KiCad and there are many tutorials online which can be helpful. This playlist in particular is very helpful if you're completely new to the software : https://www.youtube.com/watch?v=vaCVh2SAZY4&list=PL3bNyZYHcRSUhUXUt51W6nKvxx2ORvUQB 

# Definition of Done 💯 
- All requirements for this PCB outlined in the OBC design document have been satisfied. 
- All components have been selected and links to all components can be found in the project's BOM.
- Brief descriptions explaining why certain components were selected can be found in the OBC design document.
- A schematic file has been completed for the design.
- An initial PCB layout has been completed.

### Tags
@jillianmalherbe @SeanTedesco @emmapaczkowski

**Comment by SeanTedesco** [comment]
Board has been made and is in use. Closing issue.
